# Generated by Django 5.2.11 on 2026-02-11 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='InventoryManager',
        ),
    ]
